version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=sd
      - POSTGRES_PASSWORD=sd
      - POSTGRES_DB=sd
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
