version: '3.7'

services : 
  postgres:
    image: bitnami/postgresql:latest # last version of postgres image
  ports :
    - '5432:5432'
  environment :
    - POSTGRES_USER=docker # username
    - POSTGRES-PASSWORD=docker  # user password 
    - POSTGRES_DB=shareeasyf # databse name
  volumes :
    - postgres_data:/bitnami/postgresql
volumes :
  postgres_data :